### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Mamatata2** [miruchigawa/Waifu-Speech#1]
When I commented out the lines for taking audio from the microphone, nothing happens. Libraries are all installed
![photo_2023-03-19_14-16-38](https://user-images.githubusercontent.com/105057205/226171716-db6e712a-ec86-48c1-b117-b796f0eaca85.jpg)

**Comment by miruchigawa** [comment]
Yes, I have never tried it in person because my mic is broken but I will analyze and fix it asap

**Comment by Mamatata2** [comment]
Thank you)

**Comment by miruchigawa** [comment]
Please update and try again
